### ISSUE TITLE
avrdude: verification error

### ISSUE THREAD

**Issue by DzurDzen** [majekw/optiboot#2]
Hi. When I try to upload a sketch provides verification error.
avrdude: verification error, first mismatch at byte 0x0000
         0x06 != 0x07
avrdude: verification error; content mismatch

Bootloader compiled with Arduino IDE 1.5.4 and with 1.0.5 (hex are identical). I tried avrdude versions of 6.1-6.3. When flashing back to original bootloader (with usbasp), the problem disappears.

Seeeduino Mega (atmega2560) from seeedstudio.com
Windows 7
Arduino IDE 1.6.9
m2560 branch

[opti_bootloader_upload.txt](https://github.com/majekw/optiboot/files/306161/opti_bootloader_upload.txt)
[opti_sketch_upload.txt](https://github.com/majekw/optiboot/files/306162/opti_sketch_upload.txt)

**Comment by majekw** [comment]
Strange - everything looks fine except this error. I tried today with Arduino 1.6.9 and Avrdude 6.3 and it worked fine (on Linux).
Could you check this ready hex with bootloader: https://raw.githubusercontent.com/majekw/optiboot/supermaster/optiboot/bootloaders/optiboot/optiboot_atmega2560.hex ?
When you replaced Avrdude on Arduino, did you overwrote avrdude or did also something else?
I'll try to check this also on Windows later.

**Comment by DzurDzen** [comment]
I checked ready hex from supermaster branch. Everything is fine. When compiling from a m2650 branch hex a little smaller in size. Now sketches uploaded via USB and via esp-link (firmware for esp8266).
Thanks

**Comment by majekw** [comment]
@DzurDzen, could you provide .lst file for this non-working bootloader you compiled from m2560 branch? I'm curious what wrong could be with it as it should work.

**Comment by majekw** [comment]
Same issue here: http://forum.arduino.cc/index.php?topic=410068.0

**Comment by crgor** [comment]
Majek, Unfortunately I couldn't attach the lst file over there at Arduino Forum. Attached is the LST(renamed to txt) file for the optiboot supermaster branch compiled with Arduino IDE 0023 for atmega 2560.

[optiboot_atmega2560.txt](https://github.com/majekw/optiboot/files/347045/optiboot_atmega2560.txt)

**Comment by DzurDzen** [comment]
Hex and lst

[optiboot_atmega2560.hex.txt](https://github.com/majekw/optiboot/files/347052/optiboot_atmega2560.hex.txt)
[optiboot_atmega2560.lst.txt](https://github.com/majekw/optiboot/files/347053/optiboot_atmega2560.lst.txt)

**Comment by majekw** [comment]
Thank you @DzurDzen and @crgor!
I looked into these lst, but besides compiler generated code differences I can't see anything suspicious. I'll try to burn it into my Atmega2560 in following days and look what will happen.

**Comment by majekw** [comment]
This should fix this issue: https://github.com/majekw/optiboot/commit/bd0a623dfead7d60fb9766519b6891a7df224ccd

Problem was that older versions of avr-gcc shipped with Arduino earlier than 1.6.x doesn't define RAMSTART for Atmega2560, so Optiboot incorrectly assumes it's 0x100. At the beginning of memory is buffer, so some i/o registers are destroyed during upload and that leads also to flash corruption.
For me everything worked fine because I used always 1.6.x to compile things and that's why precompiled hex in supermaster is correct and works.
Thank you all for commitment, and @matthijskooijman for finding this bug.
