### ISSUE TITLE
2560 support for flashing from other uarts

### ISSUE THREAD

**Issue by uzi18** [majekw/optiboot#7]
Hi majekw
Are optiboot support flashing from different uarts?

**Comment by majekw** [comment]
@uzi18 
Yes, Optiboot supports different uarts. For example to compile bootloader for atmega2560 and UART2:
``` make atmega2560 UART=2```

**Comment by uzi18** [comment]
Ok I need 2 uarts at the same time, to be able to update firmware by usb or
port nr 2 on arduino mega

06.08.2017 1:02 AM "majekw" <notifications@github.com> napisał(a):

**Comment by majekw** [comment]
In this case it will not work. Optiboot uses only one uart and only at compile time you could choose which one.

**Comment by uzi18** [comment]
Ok will try to add such case (2nd boot uart)

06.08.2017 11:28 AM "majekw" <notifications@github.com> napisał(a):
